### ISSUE TITLE
Can't figure it out for x86_64

### ISSUE THREAD

**Issue by craignied** [joelparkerhenderson/stable-diffusion-macos-install-help#6]
Really great walkthrough, Joel. Where I'm getting hung up is

CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml

as my architecture is x86_64

I've tried

CONDA_SUBDIR=osx-x86_64 conda env create -f environment-mac.yaml

But I'm getting these  errors

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - sympy==1.10.1
  - humanfriendly==10.0
  - pytorch
  - grpcio==1.46.4
  - scipy==1.9.1
  - numpy==1.23.2
  - onnx==1.12.0
  - omegaconf==2.1.1
  - python==3.10.5
  - onnxruntime==1.12.1

Ideas? I tried pip install for them, but it's not working. Many thanks in advance.

**Comment by joelparkerhenderson** [comment]
Is it possible that you have a different installation of Anaconda or equivalent?

Can you try these diagnostic commands and copy/paste the output? You may want to omit anything private in the output, such as your username, or machine name, etc.

    % conda info
    % which conda
    % conda --version
    % more ~/.condarc

On my MacBook Pro M1 Monterey, Anaconda installs itself without any channels, and doesn't use any dot file ~/.condarc.

I don't know (yet) why your installation has channels.

When I look for the channel libuci, it doesn't seem to exist on the conda site.

You can try removing the channel like this:

     conda config --remove channels 'https://conda.anaconda.org/libuci'

You can add the channel again, if you ever want to, like this:

    conda config --add channels 'https://conda.anaconda.org/libuci'

I can also suggest you try two other ideas:

  * Search StackOverflow or similar tech sites, because the Apple Intel chip is significantly different than the Apple M1 chip; I use an M1, and don't have an Intel one to try.

  * If your goal is to run any kind of Stable Diffusion, in the past few weeks there have been a bunch of open source projects that publish one-click installers, or container installers, or websites that offer trials; if your goal is to generate images and your open to doing that in any way possible, these other ways may work better on your hardware.

**Comment by joelparkerhenderson** [comment]
No reply in a week, so I will close this issue for now. If you want to reply later, then feel free to re-open it.
